/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.*;
import config.connectDB;
import crud.reservation;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import net.proteanit.sql.DbUtils;
import panel.login;

/**
 *
 * @author vienz
 */
public class Employeereport extends javax.swing.JFrame {

    /**
     * Creates new form adminreport
     */
    public Employeereport() {
        initComponents();
        displayData();
    }
    
    public void displayData() {
    try {
        connectDB dbc = new connectDB();
        
        // Select specific columns including r_status from tbl_reservation
        String query = "SELECT r_id, r_customername, r_type, r_servicestartdate, r_cost, r_status FROM tbl_reservation";
        ResultSet rs = dbc.getData(query);
        
        // Set result set to table model
        overview.setModel(DbUtils.resultSetToTableModel(rs));

        // Set custom column headers
        overview.getColumnModel().getColumn(0).setHeaderValue("Reservation ID");
        overview.getColumnModel().getColumn(1).setHeaderValue("Customer Name");
        overview.getColumnModel().getColumn(2).setHeaderValue("Service Type");
        overview.getColumnModel().getColumn(3).setHeaderValue("Service Start");
        overview.getColumnModel().getColumn(4).setHeaderValue("Cost");
        overview.getColumnModel().getColumn(5).setHeaderValue("Status");
        
        // Refresh table headers
        overview.getTableHeader().repaint();
        
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        status = new javax.swing.JButton();
        reservation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbg.setBackground(new java.awt.Color(255, 204, 204));
        mbg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Contact Number", "Role", "Status"
            }
        ));
        jScrollPane1.setViewportView(overview);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 730, 220));

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel5.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        status.setText("OVERALL REPORT");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel5.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        reservation.setText("GET REPORT");
        reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationActionPerformed(evt);
            }
        });
        jPanel5.add(reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 490));

        mbg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 510));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setText("PureClean");
        mbg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backlogin1.png"))); // NOI18N
        jLabel8.setText("Logout");
        jLabel8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel8FocusLost(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        mbg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setText("LOGS");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        mbg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 50, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("PROFILE");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        mbg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 70, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("ACCOUNT");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        mbg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setText("DASHBOARD");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        mbg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel11.setText("RESERVATION");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        mbg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel15.setText("REPORTS");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        mbg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        displayData();
    }//GEN-LAST:event_refreshActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void jLabel8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8FocusLost

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        login log = new login();

        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        adminlogs log = new adminlogs();

        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        account acc = new account();

        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        accountmanager man = new accountmanager();

        man.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        adminreservation reservation = new adminreservation();  // Create a new instance of reservation panel
        reservation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Employeereport arp = new Employeereport();
        arp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationActionPerformed
        
     int selectedRow = overview.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a reservation from the table first.");
        return;
    }

    // Extract values from the 6 visible columns
    String customer = overview.getValueAt(selectedRow, 1).toString(); // r_customername
    String type = overview.getValueAt(selectedRow, 2).toString();     // r_type
    String startDate = overview.getValueAt(selectedRow, 3).toString(); // r_servicestartdate
    String cost = overview.getValueAt(selectedRow, 4).toString();     // r_cost
    String status = overview.getValueAt(selectedRow, 5).toString();   // r_status
    String id = overview.getValueAt(selectedRow, 0).toString();       // r_id (if needed)

    // Fetch the additional 2 columns (r_creationdate, r_cnumber, r_location) from the database
    try {
        connectDB dbc = new connectDB();
        String query = "SELECT r_creationdate, r_cnumber, r_location FROM tbl_reservation WHERE r_id = ?";
        PreparedStatement pst = dbc.getConnection().prepareStatement(query);
        pst.setString(1, id); // Use the r_id to fetch the additional columns
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String creationDate = rs.getString("r_creationdate");
            String contactNumber = rs.getString("r_cnumber");
            String location = rs.getString("r_location");

            // Format and show details in a dialog
            StringBuilder details = new StringBuilder();
            details.append("Customer: ").append(customer).append("\n");
            details.append("Type: ").append(type).append("\n");
            details.append("Start Date: ").append(startDate).append("\n");
            details.append("Cost: ").append(cost).append("\n");
            details.append("Status: ").append(status).append("\n");
            details.append("Creation Date: ").append(creationDate).append("\n");
            details.append("Contact: ").append(contactNumber).append("\n");
            details.append("Location: ").append(location).append("\n");

            // Show the details in a JOptionPane dialog
            JOptionPane.showMessageDialog(null, details.toString(), "Reservation Details", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading additional data: " + e.getMessage());
    }




    }//GEN-LAST:event_reservationActionPerformed
public void generateReport() {
    try {
        connectDB dbc = new connectDB();
        
        // Query to get 8 columns
        String query = "SELECT r_customername, r_type, r_creationdate, r_servicestartdate, r_status, r_cost, r_cnumber, r_location FROM tbl_reservation";
        ResultSet rs = dbc.getData(query);
        
        // Display in the JTable named 'overview'
        overview.setModel(DbUtils.resultSetToTableModel(rs));

        // Set headers for the 8 columns
        overview.getColumnModel().getColumn(0).setHeaderValue("Customer Name");
        overview.getColumnModel().getColumn(1).setHeaderValue("Service Type");
        overview.getColumnModel().getColumn(2).setHeaderValue("Creation Date");
        overview.getColumnModel().getColumn(3).setHeaderValue("Service Start Date");
        overview.getColumnModel().getColumn(4).setHeaderValue("Status");
        overview.getColumnModel().getColumn(5).setHeaderValue("Cost");
        overview.getColumnModel().getColumn(6).setHeaderValue("Contact Number");
        overview.getColumnModel().getColumn(7).setHeaderValue("Location");
        
        overview.getTableHeader().repaint();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error loading data: " + ex.getMessage());
    }
}


//public void showReportInDialog() {
//    try {
//        connectDB dbc = new connectDB();
//
//        String query = "SELECT r_customername, r_type, r_creationdate, r_servicestartdate, r_status, r_cost, r_cnumber, r_location FROM tbl_reservation";
//        ResultSet rs = dbc.getData(query);
//
//        StringBuilder report = new StringBuilder();
//        while (rs.next()) {
//            report.append("Customer: ").append(rs.getString("r_customername")).append("\n");
//            report.append("Type: ").append(rs.getString("r_type")).append("\n");
//            report.append("Created: ").append(rs.getString("r_creationdate")).append("\n");
//            report.append("Start Date: ").append(rs.getString("r_servicestartdate")).append("\n");
//            report.append("Status: ").append(rs.getString("r_status")).append("\n");
//            report.append("Cost: ").append(rs.getString("r_cost")).append("\n");
//            report.append("Contact: ").append(rs.getString("r_cnumber")).append("\n");
//            report.append("Location: ").append(rs.getString("r_location")).append("\n");
//            report.append("------------------------------------------------------\n");
//        }
//
//        JTextArea textArea = new JTextArea(report.toString());
//        textArea.setEditable(false);
//        JScrollPane scrollPane = new JScrollPane(textArea);
//        scrollPane.setPreferredSize(new Dimension(500, 400));
//
//        JOptionPane.showMessageDialog(null, scrollPane, "Reservation Report", JOptionPane.INFORMATION_MESSAGE);
//
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
//    }
//}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeereport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeereport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mbg;
    private javax.swing.JTable overview;
    private javax.swing.JButton refresh;
    private javax.swing.JButton reservation;
    private javax.swing.JButton status;
    // End of variables declaration//GEN-END:variables
}
