/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import admin.adminDB;
import config.DBLogger;
import config.connectDB;
import config.hasher;
import config.session;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vienz
 */

public class login extends javax.swing.JFrame {
public static int loggedInUserId;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    
    
    
    public String[] loginAcc(String email, String password) {
    connectDB con = new connectDB();

    try {
        String query = "SELECT u_hashpw, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim());
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            String storedHashedPassword = resultSet.getString("u_hashpw");
            String hashedInputPassword = hasher.hashPassword(password); // Hash input password

            // Compare hashed input with stored hash
            if (hashedInputPassword.equals(storedHashedPassword)) {
                return new String[]{resultSet.getString("u_type").trim(), resultSet.getString("u_status").trim()};
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if login fails
}


    
    public String[] getUserDetails(String email) {
    connectDB con = new connectDB();
    try {
        String query = "SELECT u_id, u_firstname, u_lastname, u_email, u_contactnumber, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim()); // Set email as the query parameter
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            return new String[]{
                resultSet.getString("u_id").trim(),
                resultSet.getString("u_firstname").trim(),
                resultSet.getString("u_lastname").trim(),
                resultSet.getString("u_email").trim(),
                resultSet.getString("u_contactnumber").trim(),
                resultSet.getString("u_type").trim(),
                resultSet.getString("u_status").trim()
            };
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if no user is found
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        logintext = new javax.swing.JLabel();
        registerbutton = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        forgotpassword1 = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        requireduser = new javax.swing.JLabel();
        requiredpass = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 185, 185));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        logintext.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logintext.setText("Login");

        registerbutton.setText("Don't have an account? Register here");
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
        });

        loginbutton.setBackground(new java.awt.Color(241, 185, 185));
        loginbutton.setText("Login");
        loginbutton.setBorderPainted(false);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        forgotpassword1.setText("Forgot password");
        forgotpassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassword1MouseClicked(evt);
            }
        });

        emailtext.setText("Email");

        passtext.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requiredpass, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailtext)
                                .addComponent(logintext)
                                .addComponent(registerbutton)
                                .addComponent(forgotpassword1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username)
                                .addComponent(loginbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(passtext)
                                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                            .addGap(51, 51, 51))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(requireduser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logintext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerbutton)
                .addGap(18, 18, 18)
                .addComponent(emailtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requireduser, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiredpass, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(loginbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotpassword1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10); 
username.setFont(smallFont); 
requireduser.setFont(smallFont); 

String user = username.getText();

if (user.isEmpty()) {
    username.setForeground(Color.RED);
    requireduser.setText("Username is required");
    requireduser.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requireduser.setText("");
}

username.repaint();
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
Font smallFont = new Font("Arial", Font.PLAIN, 10);
password.setFont(smallFont); 
requiredpass.setFont(smallFont); 

String user = password.getText();

if (user.isEmpty()) {
    password.setForeground(Color.RED);
    requiredpass.setText("Password is required");
    requiredpass.setForeground(Color.RED);
} else {
    username.setForeground(Color.BLACK);
    requiredpass.setText("");
}

password.repaint();
    }//GEN-LAST:event_passwordFocusLost

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        register reg = new register();

        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerbuttonMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String user = username.getText().trim();
String pass = password.getText().trim();

if (user.isEmpty() || pass.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Username and/or password cannot be empty.", "Login Error", JOptionPane.ERROR_MESSAGE);
    username.requestFocus();
    return;
}

try {
    // Directly use the entered username and password without hashing
    String[] loginData = loginAcc(user, pass);

    if (loginData == null) {
        // Failed login attempt
        DBLogger.log(user, "Failed login attempt", loggedInUserId);
        JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        password.requestFocus();
        return;
    }

    String[] userDetails = getUserDetails(user);

    String userID = userDetails[0]; // This is the user ID
    String firstName = userDetails[1];
    String lastName = userDetails[2];
    String email = userDetails[3];
    String contactNumber = userDetails[4];
    String accType = loginData[0];
    String accStatus = loginData[1];

    if (!"active".equalsIgnoreCase(accStatus)) {
        // Account is not active
        DBLogger.log(user, "Inactive account login attempt", loggedInUserId);
        JOptionPane.showMessageDialog(this, "Your account is still pending. Please contact the administrator.", "Login Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    session sess = session.getInstance();
    sess.setU_id(userID);
    sess.setUsername(user);
    sess.setFirstName(firstName);
    sess.setLastName(lastName);
    sess.setEmail(email);
    sess.setContact(contactNumber);
    sess.setAcc_type(accType);
    sess.setAcc_status(accStatus);

    // Now use userID as the logged-in user ID when logging the login action
    if (accType != null) {
        if ("Admin".equalsIgnoreCase(accType)) {
            DBLogger.log(user, "Admin logged in", Integer.parseInt(userID));   // Log successful login for Admin
            new adminDB().setVisible(true);
        } else if ("Employee".equalsIgnoreCase(accType)) {
            DBLogger.log(user, "Employee logged in", Integer.parseInt(userID));   // Log successful login for Employee
            new ereservation().setVisible(true);
        } else {
            // Invalid user type
            DBLogger.log(user, "Unknown user type login attempt", Integer.parseInt(userID)); 
            JOptionPane.showMessageDialog(this, "Unknown user type!", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.dispose(); // Close login window
    } else {
        // Invalid login credentials
        DBLogger.log(user, "Incorrect login credentials", Integer.parseInt(userID));  // Log incorrect credentials attempt
        JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        password.requestFocus();
    }

} catch (Exception e) {
    // Log error during login
    DBLogger.log(user, "Error during login: " + e.getMessage(), 0);  // Log error (0 for unknown user ID)
    JOptionPane.showMessageDialog(this, "Error during login: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void forgotpassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassword1MouseClicked
        forgotpassword fp = new forgotpassword();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotpassword1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel forgotpassword1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel passtext;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel requiredpass;
    private javax.swing.JLabel requireduser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
